Repository enrique-lozano/Monekin, pull requests merged in 2024-12, with the labels that each got.

#259 Improve settings performance and fix initially wrong blur state in the amounts
  lib/app/currencies/currency_manager.dart
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/home_drawer.dart
  lib/app/layout/navigation_sidebar.dart
  lib/app/onboarding/onboarding.dart
  lib/app/settings/appearance_settings_page.dart
  lib/app/settings/edit_profile_modal.dart
  lib/app/settings/widgets/monekin_tile_switch.dart
  lib/core/database/app_db.dart
  lib/core/database/services/app-data/app_data_service.dart
  lib/core/database/services/currency/currency_service.dart
  lib/core/database/services/shared/key_value_pair.dart
  lib/core/database/services/shared/key_value_service.dart
  lib/core/database/services/user-setting/private_mode_service.dart
  lib/core/database/services/user-setting/user_setting_service.dart
  lib/core/database/services/user-setting/utils/get_theme_from_string.dart
  lib/core/presentation/widgets/number_ui_formatters/currency_displayer.dart
  lib/core/utils/debouncer.dart
  lib/main.dart
Labels: type: enhancement

#267 Display compact currencies in some places to avoid UI overflows
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/dashboard_cards.dart
  lib/app/home/widgets/horizontal_scrollable_account_list.dart
  lib/app/home/widgets/income_or_expense_card.dart
  lib/app/transactions/recurrent_transactions_page.dart
  lib/core/presentation/responsive/app_breakpoints.dart
  lib/core/presentation/widgets/number_ui_formatters/currency_displayer.dart
  lib/core/presentation/widgets/number_ui_formatters/ui_number_formatter.dart
Labels: type: bug

#270 Change transactions icon in the tabs
  lib/core/routes/destinations.dart
Labels: type: enhancement

#272 Fix potential overflow with large amounts in the transaction form and in the amount selector
  lib/app/transactions/form/dialogs/amount_selector.dart
  lib/app/transactions/form/transaction_form.page.dart
  lib/core/presentation/widgets/number_ui_formatters/ui_number_formatter.dart
Labels: type: bug

#273 Upgrade android platform
  .metadata
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/kotlin/com/example/monekin/MainActivity.kt
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
Labels: type: build, platform: android

#274 Add Hungarian language
  lib/app/settings/widgets/supported_locales.dart
  lib/i18n/README.md
  lib/i18n/strings_hu.json
  lib/i18n/translations.g.dart
Labels: type: enhancement

#275 New behaviour and animation for the "New transaction" button
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/new_transaction_fl_button.dart
  lib/app/layout/navigation_sidebar.dart
  lib/app/transactions/transactions.page.dart
  lib/app/transactions/widgets/transaction_list.dart
Labels: type: enhancement, UI / UX

#276 Remove "New transaction" button from the navigation drawer
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/home_drawer.dart
  lib/app/home/widgets/navigation_drawer.dart
  lib/app/layout/navigation_sidebar.dart
  lib/app/onboarding/intro.page.dart
  lib/app/settings/about_page.dart
  lib/app/settings/help_us_page.dart
  lib/app/settings/widgets/display_app_icon.dart
Labels: type: enhancement

#277 Improve UI/UX in large screens
  lib/app/budgets/budget_details_page.dart
  lib/app/budgets/budgets_page.dart
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/navigation_drawer.dart
  lib/app/layout/navigation_sidebar.dart
  lib/app/stats/stats_page.dart
  lib/app/transactions/transactions.page.dart
  lib/main.dart
Labels: type: enhancement, UI / UX

#278 Lost tags when cloning or editing transactions
  lib/app/categories/form/category_form_functions.dart
  lib/app/transactions/form/transaction_form.page.dart
  lib/app/transactions/transaction_details.page.dart
  lib/app/transactions/widgets/bulk_edit_transaction_modal.dart
  lib/core/database/services/transaction/transaction_service.dart
  lib/core/models/transaction/transaction.dart
  lib/core/services/view-actions/transaction_view_actions_service.dart
Labels: type: bug

#283 Accepting a recurring transaction payment don't create a new transaction
  lib/app/transactions/transaction_details.page.dart
  lib/app/transactions/widgets/translucent_transaction_status_card.dart
  lib/core/database/services/transaction/transaction_service.dart
Labels: type: bug

#285 No amount and title when editing an item in category for 'Both'
  lib/app/transactions/form/transaction_form.page.dart
Labels: type: bug

#286 Add some missing translations
  lib/core/models/transaction/next_pay_status.enum.dart
  lib/i18n/strings_en.json
  lib/i18n/strings_es.json
  lib/i18n/strings_hu.json
  lib/i18n/strings_uk.json
  lib/i18n/strings_zh-TW.json
  lib/i18n/translations.g.dart
  pubspec.lock
Labels: type: bug
