Repository enrique-lozano/Monekin, pull requests merged in 2025-03, with the labels that each got.

#324 Improve date period selector
  lib/app/accounts/account_selector.dart
  lib/app/categories/form/icon_and_color_selector.dart
  lib/app/categories/selectors/category_multi_selector.dart
  lib/app/categories/selectors/category_picker.dart
  lib/app/currencies/exchange_rate_form.dart
  lib/app/home/dashboard.page.dart
  lib/app/home/widgets/income_or_expense_card.dart
  lib/app/home/widgets/navigation_drawer.dart
  lib/app/layout/navigation_sidebar.dart
  lib/app/settings/widgets/language_selector.dart
  lib/app/stats/stats_page.dart
  lib/app/stats/widgets/fund_evolution_line_chart.dart
  lib/app/tags/tags_selector.modal.dart
  lib/core/extensions/date.extensions.dart
  lib/core/models/date-utils/date_period_state.dart
  lib/core/presentation/app_colors.dart
  lib/core/presentation/theme.dart
  lib/core/presentation/widgets/currency_selector_modal.dart
  lib/core/presentation/widgets/dates/date_period_modal.dart
  lib/core/presentation/widgets/dates/segmented_calendar_button.dart
  lib/core/presentation/widgets/dynamic-selector-modal.dart
  lib/core/presentation/widgets/icon_selector_modal.dart
  lib/core/presentation/widgets/monekin_dropdown_select.dart
  lib/core/presentation/widgets/tappable-text-entry.dart
  lib/core/presentation/widgets/transaction_filter/filter_sheet_modal.dart
Labels: type: enhancement

#325 Fund evolution chart without info in "always" date period
  lib/app/stats/utils/common_axis_titles.dart
  lib/app/stats/widgets/fund_evolution_line_chart.dart
  lib/core/database/services/account/account_service.dart
Labels: type: bug

#327 Simplified Chinese language support added
  lib/app/settings/widgets/supported_locales.dart
  lib/i18n/generated/translations.g.dart
  lib/i18n/generated/translations_zh_CN.g.dart
  lib/i18n/json/zh-CN.json
Labels: type: enhancement, Translations
