Repository enrique-lozano/Monekin, pull requests merged in 2025-01, with the labels that each got.

#289 +25 completely new icons
  assets/icons/supported_selectable_icons/entertainment/playing_cards.svg
  assets/icons/supported_selectable_icons/food/egg_alt.svg
  assets/icons/supported_selectable_icons/food/grocery.svg
  assets/icons/supported_selectable_icons/food/local_cafe.svg
  assets/icons/supported_selectable_icons/food/restaurant.svg
  assets/icons/supported_selectable_icons/medical/clean_hands.svg
  assets/icons/supported_selectable_icons/medical/elderly.svg
  assets/icons/supported_selectable_icons/medical/elderly_woman.svg
  assets/icons/supported_selectable_icons/medical/pregnant_woman.svg
  assets/icons/supported_selectable_icons/medical/pulmonology.svg
  assets/icons/supported_selectable_icons/medical/sanitizer.svg
  assets/icons/supported_selectable_icons/money/assured_workload.svg
  assets/icons/supported_selectable_icons/money/credit_card_heart.svg
  assets/icons/supported_selectable_icons/money/money_bag.svg
  assets/icons/supported_selectable_icons/money/money_bag_star.svg
  assets/icons/supported_selectable_icons/money/universal_currency_alt.svg
  assets/icons/supported_selectable_icons/other/child_care.svg
  assets/icons/supported_selectable_icons/other/hotel_class.svg
  assets/icons/supported_selectable_icons/other/mode_heat.svg
  assets/icons/supported_selectable_icons/other/pet_supplies.svg
  assets/icons/supported_selectable_icons/other/potted_plant.svg
  assets/icons/supported_selectable_icons/other/school.svg
  assets/icons/supported_selectable_icons/other/shower.svg
  assets/icons/supported_selectable_icons/other/yard.svg
  assets/icons/supported_selectable_icons/technology/desktop_cloud_stack.svg
  assets/icons/supported_selectable_icons/technology/smb_share.svg
  assets/icons/supported_selectable_icons/transport/ev_station.svg
  assets/icons/supported_selectable_icons/transport/garage.svg
  lib/core/services/supported_icon/getter/supported_icons.dart
  lib/core/services/supported_icon/getter/supported_icons.json
  pubspec.lock
Labels: type: enhancement

#293 Custom color picker
  lib/app/accounts/account_form.dart
  lib/app/categories/form/icon_and_color_selector.dart
  lib/app/settings/appearance_settings_page.dart
  lib/app/tags/tag_form_page.dart
  lib/core/extensions/color.extensions.dart
  lib/core/models/supported-icon/supported_icon.dart
  lib/core/presentation/widgets/color_picker/color_picker_modal.dart
  lib/core/presentation/widgets/color_picker/custom_color_picker.dart
  lib/core/presentation/widgets/color_picker/custom_color_picker_modal.dart
  lib/core/presentation/widgets/gradient-box.borders.dart
  lib/core/presentation/widgets/modal_container.dart
  lib/core/presentation/widgets/reorderable_drag_icon.dart
  lib/core/presentation/widgets/simple_shadow.dart
  lib/i18n/strings_de.json
  lib/i18n/strings_en.json
  lib/i18n/strings_es.json
  lib/i18n/strings_hu.json
  lib/i18n/strings_uk.json
  lib/i18n/strings_zh-TW.json
  lib/i18n/translations.g.dart
  pubspec.lock
  pubspec.yaml
Labels: type: enhancement

#294 Wrong states and UI bugs in the sliver appbar headers
  lib/app/accounts/details/account_details.dart
  lib/app/transactions/transaction_details.page.dart
Labels: type: bug

#295 New theme dropdown and setting icons animations
  lib/app/settings/appearance_settings_page.dart
  lib/app/settings/widgets/monekin_tile_switch.dart
  lib/core/database/services/user-setting/utils/get_theme_from_string.dart
  lib/core/presentation/widgets/monekin_dropdown_select.dart
  lib/i18n/strings_de.json
  lib/i18n/strings_en.json
  lib/i18n/strings_es.json
  lib/i18n/strings_hu.json
  lib/i18n/strings_uk.json
  lib/i18n/strings_zh-TW.json
  lib/i18n/translations.g.dart
Labels: type: enhancement

#298 Translation zh_TW updates
  lib/i18n/strings_zh-TW.json
Labels: Translations

#302 Allow choosing a custom directory for local backups
  lib/app/settings/export_page.dart
  lib/core/database/backup/backup_database_service.dart
  lib/core/utils/get_download_path.dart
Labels: type: enhancement, status: READY
